version: '3.4'
services:
  chat:
    build: .
    ports:
      - "9080:9080"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - .:/code
    links:
      - "redis"
  redis:
    image: "redis:6.0-rc2-alpine3.11"
    ports:
      - 6379:6379
